### ISSUE TITLE
Broken link in the docs

### ISSUE THREAD

**Issue by michael-soorys** [teamstarter/graphql-sequelize-generator#19]
https://vincent-desmares.gitbook.io/graphql-sequelize-generator/resolvers/performances

The <b> graphql-sequelize </b> link has an extra "]" at the end so the link doesn't lead to the actual github repo.

**Comment by vincentdesmares** [comment]
@michael-soorys Thanks for spotting it! It's now fixed.

If you have other corrections or improvements to suggest, don't hesitate!
