### ISSUE TITLE
Add support for others Apollo servers (Hapi,Koa,etc)

### ISSUE THREAD

**Issue by BaumDigital** [teamstarter/graphql-sequelize-generator#3]
Hi.
I would like to suggest a feature: The ability to chose which apollo server to use on the generateApolloServer function, since at the moment allow works on express.
For example: apollo-server-hapi or require('apollo-server-koa')
Best regards.

**Comment by vincentdesmares** [comment]
Hi @BaumDigital, sorry I totally missed your request! Are you still interested by this feature?
