### ISSUE TITLE
Duplicate Enum type error when using ENUM(...) datataype in the model

### ISSUE THREAD

**Issue by armenhajian** [teamstarter/graphql-sequelize-generator#31]
Error: Schema must contain uniquely named types but contains multiple types named "quiztestEnumType"

This is my model

`const Model = sequelize.define('quiz', {

        id: {
            type: DataTypes.INTEGER,
            allowNull: false,
            autoIncrement: true,
            primaryKey: true,
        },

        title: {
            type: DataTypes.STRING,
            allowNull: false,
        },

        test: {
            type: DataTypes.ENUM(['one', 'two']),
        }

    }, Object.assign({}, defaultOptions));`

P.S. I don't have any other Enum type in my project.

**Comment by vincentdesmares** [comment]
Hi @armenhajian , I will be looking at this issue soon. Thanks for the report!

**Comment by vincentdesmares** [comment]
It looks like this was resolved with this PR on graphql-sequelize: [https://github.com/mickhansen/graphql-sequelize/pull/698/files](https://github.com/mickhansen/graphql-sequelize/pull/698/files). I tried to upgrade but it's still not working, I will try to dig into this further next week.

**Comment by vincentdesmares** [comment]
No answers.

**Comment by vincentdesmares** [comment]
Closed as stale.
